version: "3.4"
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: on-failure
    ports:
      - ${PHPMYADMIN_PORT}:80
    depends_on:
      - db

  gateway:
    volumes:
        - alchemy_vol:/var/alchemy/Phraseanet

  phraseanet:
    #environment:
      #- DOCKER_XDEBUG_ENABLED
      #- PHP_IDE_CONFIG=serverName=${SERVER_NAME}
    volumes:
      - alchemy_vol:/var/alchemy/Phraseanet

  worker:
    volumes:
      - alchemy_vol:/var/alchemy/Phraseanet

  rabbitmq:
    ports:
      - ${RABBITMQ_MANAGEMENT_PORT}:15672

volumes:
  alchemy_vol:
    driver: local
    driver_opts:
      type: none
      device: ${ALCHEMY_WORKSPACE_DIR}
      o: bind
