version: "3.4"

services:
  gateway:
    image: $PHRASEANET_DOCKER_REGISTRY/phraseanet-nginx:$PHRASEANET_DOCKER_TAG
    restart: on-failure
    volumes:
        - data_vol:/var/alchemy/Phraseanet/datas:rw
        - custom_vol:/var/alchemy/Phraseanet/www/custom:rw
        - thumbnails_vol:/var/alchemy/Phraseanet/www/thumbnails:rw
    depends_on:
      - phraseanet
    environment:
      - MAX_BODY_SIZE

    ports:
      - ${PHRASEANET_APP_PORT}:80

  phraseanet:
    image: $PHRASEANET_DOCKER_REGISTRY/phraseanet-fpm:$PHRASEANET_DOCKER_TAG
    restart: on-failure
    depends_on:
      - db
      - redis
      - rabbitmq
      - elasticsearch
    environment:
    - MAX_BODY_SIZE
    - MAX_INPUT_VARS
    - OPCACHE_ENABLED
    - SESSION_CACHE_LIMITER
    - PHP_LOG_LEVEL
    - INSTALL_ACCOUNT_EMAIL
    - INSTALL_ACCOUNT_PASSWORD
    - INSTALL_DB_HOST
    - INSTALL_DB_PORT
    - INSTALL_DB_USER
    - INSTALL_DB_PASSWORD
    - INSTALL_DB_TEMPLATE
    - INSTALL_APPBOX
    - INSTALL_DATABOX
    - INSTALL_SERVER_NAME
    - INSTALL_RABBITMQ_USER=$RABBITMQ_DEFAULT_USER
    - INSTALL_RABBITMQ_PASSWORD=$RABBITMQ_DEFAULT_PASS
    volumes:
      - data_vol:/var/alchemy/Phraseanet/datas:rw
      - config_vol:/var/alchemy/Phraseanet/config:rw
      - tmp_vol:/var/alchemy/Phraseanet/tmp:rw
      - tmp_locks_vol:/var/alchemy/Phraseanet/tmp/locks:rw
      - tmp_caption_vol:/var/alchemy/Phraseanet/tmp/caption:rw
      - tmp_lazaret_vol:/var/alchemy/Phraseanet/tmp/lazaret:rw
      - tmp_download_vol:/var/alchemy/Phraseanet/tmp/download:rw
      # @TODO : waiting for a resolution
      - resources_proxy:/var/alchemy/Phraseanet/resources/proxies:rw
      - logs_vol:/var/alchemy/Phraseanet/logs:rw
      - thumbnails_vol:/var/alchemy/Phraseanet/www/thumbnails:rw

  worker:
    image: $PHRASEANET_DOCKER_REGISTRY/phraseanet-worker:$PHRASEANET_DOCKER_TAG
    restart: on-failure
    depends_on:
      - db
      - redis
      - rabbitmq
      - elasticsearch
    environment:
    - MAX_BODY_SIZE
    - MAX_INPUT_VARS
    - OPCACHE_ENABLED
    - SESSION_CACHE_LIMITER
    - PHP_LOG_LEVEL

    volumes:
      - data_vol:/var/alchemy/Phraseanet/datas:rw
      - config_vol:/var/alchemy/Phraseanet/config:rw
      - tmp_vol:/var/alchemy/Phraseanet/tmp:rw
      - tmp_locks_vol:/var/alchemy/Phraseanet/tmp/locks:rw
      - tmp_caption_vol:/var/alchemy/Phraseanet/tmp/caption:rw
      - tmp_lazaret_vol:/var/alchemy/Phraseanet/tmp/lazaret:rw
      - tmp_download_vol:/var/alchemy/Phraseanet/tmp/download:rw
      # @TODO : waiting for a resolution
      - resources_proxy:/var/alchemy/Phraseanet/resources/proxies:rw
      - logs_vol:/var/alchemy/Phraseanet/logs:rw
      - thumbnails_vol:/var/alchemy/Phraseanet/www/thumbnails:rw

  db:
    image: $PHRASEANET_DOCKER_REGISTRY/phraseanet-db:$PHRASEANET_DOCKER_TAG
    build: ./db
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_MAX_ALLOWED_PACKET
    volumes:
     - db_vol:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    restart: on-failure
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS

  redis:
    image: redis
    restart: on-failure

  elasticsearch:
    image: $PHRASEANET_DOCKER_REGISTRY/phraseanet-elasticsearch:$PHRASEANET_DOCKER_TAG
    build: ./elasticsearch
    restart: on-failure
    volumes:
      - elasticsearch_vol:/usr/share/elasticsearch/data

volumes:
  data_vol:
    driver: local
    driver_opts:
      type: none
      device: $VOLUMES_DIR/data
      o: bind
  tmp_vol:
    driver: local
  tmp_locks_vol:
    driver: local
  tmp_caption_vol:
    driver: local
  tmp_lazaret_vol:
    driver: local
  tmp_download_vol:
    driver: local
  db_vol:
    driver: local
  elasticsearch_vol:
    driver: local
  dev_vol:
    driver: local
  config_vol:
    driver: local
    driver_opts:
      type: none
      device: $VOLUMES_DIR/config
      o: bind
  custom_vol:
    driver: local
  thumbnails_vol:
    driver: local
    driver_opts:
      type: none
      device: $VOLUMES_DIR/thumbnails
      o: bind
  # to be replacer by stdout/stderr
  logs_vol:
    driver: local
    driver_opts:
      type: none
      device: $VOLUMES_DIR/logs
      o: bind
  # @TODO : waiting for a resolution
  resources_proxy:
    driver: local
