version: "3.4"

networks:
  default:
    ipam:
      config:
        - subnet: $DOCKER_NETWORK_CIDR

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: on-failure
    ports:
      - ${PHPMYADMIN_PORT}:80
    depends_on:
      - db

  gateway:
    volumes:
        - alchemy_vol:/var/alchemy/Phraseanet

  phraseanet:
    volumes:
      - alchemy_vol:/var/alchemy/Phraseanet

  worker:
    volumes:
      - alchemy_vol:/var/alchemy/Phraseanet

  rabbitmq:
    ports:
      - ${RABBITMQ_MANAGEMENT_PORT}:15672

  mailhog:
      image: mailhog/mailhog
      ports:
      - 1025:1025
      - 8025:8025

volumes:
  alchemy_vol:
    driver: local
    driver_opts:
      type: none
      device: ${ALCHEMY_WORKSPACE_DIR}
      o: bind
