version: "3.4"
networks:
  default:
    ipam:
      config:
        - subnet: $SUBNET_IPS

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: on-failure
    ports:
      - ${PHPMYADMIN_PORT}:80
    depends_on:
      - db

  gateway:
    volumes:
        - alchemy_vol:/var/alchemy/Phraseanet

  phraseanet:
    image: $PHRASEANET_DOCKER_REGISTRY/phraseanet-fpm-xdebug:$PHRASEANET_DOCKER_TAG
    ports:
    - $XDEBUG_PHRASEANET_PORT:9000
    volumes:
      - alchemy_vol:/var/alchemy/Phraseanet
    environment:
    - XDEBUG_CONFIG=remote_enable=1 remote_host=${GATEWAY_IP} idekey=PHPSTORM
    - XDEBUG_REMOTE_HOST=${GATEWAY_IP}

  worker:
    image: $PHRASEANET_DOCKER_REGISTRY/phraseanet-worker-xdebug:$PHRASEANET_DOCKER_TAG
    ports:
    - $XDEBUG_WORKER_PORT:9000
    volumes:
      - alchemy_vol:/var/alchemy/Phraseanet

  rabbitmq:
    ports:
      - ${RABBITMQ_MANAGEMENT_PORT}:15672

  mailhog:
      image: mailhog/mailhog
      ports:
      - 1025:1025
      - 8025:8025

volumes:
  alchemy_vol:
    driver: local
    driver_opts:
      type: none
      device: ${ALCHEMY_WORKSPACE_DIR}
      o: bind
